### ISSUE TITLE
same zones for several scripts?

### ISSUE THREAD

**Issue by RosaWagner** [Mark2Mark/mark-zones-plugin#7]
I am trying to apply the same zones for several scripts, I tried to enter: `Latin Greek`, `Latin_Greek`, `Latin, Greek`. Since it didn't work I wonder if it is possible without duplicating the zones in the custome parameter?

**Comment by Mark2Mark** [comment]
Hi Rosalie, thanks for this. 
It seems not possible at the moment, but I'll see what I can do to make it happen. Good idea! Didn't have that use case yet 👌

**Comment by Mark2Mark** [comment]
@RosaWagner, I already got it working.

For the moment, how would it be to write it like this `Latin + Greek`?

I cannot use the comma and underscore, as they are alrady used to split the custom parameter value when parsing (it is all stored as a simple string).

A space seems a little unexplanatory to me and an ampersand looks a little messy.

I could also think about using predicates in the future, if that ever comes up as a need, for example exlude something via leading exclam `!latin` (but for now I cannot think of much use for that. Your idea seems pretty useful, though.

**Comment by RosaWagner** [comment]
`+` is fine by me :)

**Comment by Mark2Mark** [comment]
Thank you!

Just pushed version 1.3.1 which should make it work. Normally Glyphs should pull the update automatically soon. Let me know if it doesn’t :)

closed with 707c030a7f1a72544f0dc089c865808e65289933
