### ISSUE TITLE
window to purchase license doesn't appear anymore although still trial

### ISSUE THREAD

**Issue by RosaWagner** [Mark2Mark/mark-zones-plugin#8]
I was on the trial version and it's been a few days that I want to purchase the license, but the window stopped appearing and no option for purchase when right click etc.

**Comment by Mark2Mark** [comment]
Thanks for letting me know @RosaWagner 

When you right click in the edit view, does the context menu show a "Purchase Mark Zones" menu item?

I'll have a look ...

**Comment by Mark2Mark** [comment]
This should be fixed with version 1.3.2, which is currently deployed and should be fetched by Glyphs very soon.

Please let me know if that helped :)

Thanks for the report, much appreciated 💚

**Comment by Mark2Mark** [comment]
Hi @DavidMS1987
First of all: many thanks for your support!

May I ask what exactly is not working for you? Normally, if you go through the purchase process, the plugin is activated right away. You should also have gotten an email with the invoice and your license key. The key might already be entered automatically for you, though.

So in summary, if you purchased it, you have licensed it :)

Does that help? Let me know if there’s anything else I can help you with.

**Comment by DavidMS1987** [comment]
Yes that hepls!! I dint'd imagine the key was automatically entered for me. I was trying to find where to enter it! Okay, sorry about this stupid question and thanks for quickly answering! :)

**Comment by Mark2Mark** [comment]
Not a stupid question!
I am glad to hear all works for you. In case the license window ever shows again, you will also see a button "Enter License". That’s where you can re-enter the lincese key, if necessary.

Closing this for now, as it should be fixed. Feel free to re-open, if the trial window does not show, even though you’re in a trial.

**Comment by RosaWagner** [comment]
@Mark2Mark sorry for the late reply, it worked! thanks a lot :)
